# -*- coding: utf-8 -*-
"""pbmc3k_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rClWsH6osmAh-VYwDpimItBKVEYE5R6_
"""

pip install scanpy anndata matplotlib seaborn pandas numpy

#Import Libraries & Load Data
import scanpy as sc
import pandas as pd
import numpy as np

# Fix the deprecation warning
sc.set_figure_params(dpi=80, facecolor='white')
sc.settings.verbosity = 3

# This automatically downloads the PBMC 3k dataset for you
# No manual file download needed
adata = sc.datasets.pbmc3k()

print(adata)

import scanpy as sc

sc.settings.verbosity = 3
sc.set_figure_params(dpi=80, facecolor='white')  # fixed deprecation warning

results_file = 'pbmc3k.h5ad'  # where we'll save results at the end

adata = sc.datasets.pbmc3k()
adata.var_names_make_unique()
print(adata)

sc.pp.filter_cells(adata, min_genes=200)   # remove cells with fewer than 200 genes
sc.pp.filter_genes(adata, min_cells=3)     # remove genes found in fewer than 3 cells

print(adata)

# Flag mitochondrial genes (start with "MT-")
adata.var['mt'] = adata.var_names.str.startswith('MT-')

# Calculate QC metrics
sc.pp.calculate_qc_metrics(
    adata, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True
)

sc.pl.violin(
    adata,
    ['n_genes_by_counts', 'total_counts', 'pct_counts_mt'],
    jitter=0.4,
    multi_panel=True
)

sc.pl.scatter(adata, x='total_counts', y='pct_counts_mt')
sc.pl.scatter(adata, x='total_counts', y='n_genes_by_counts')

adata = adata[adata.obs.n_genes_by_counts < 2500, :]
adata = adata[adata.obs.pct_counts_mt < 5, :]

print(f"Cells remaining after QC: {adata.n_obs}")

sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

sc.pp.highly_variable_genes(
    adata,
    min_mean=0.0125,
    max_mean=3,
    min_disp=0.5
)

sc.pl.highly_variable_genes(adata)

# Store full data in .raw before filtering to HVGs
adata.raw = adata

# Keep only highly variable genes
adata = adata[:, adata.var.highly_variable]

print(f"Highly variable genes: {adata.n_vars}")

# Remove effect of total counts and % mitochondrial reads
sc.pp.regress_out(adata, ['total_counts', 'pct_counts_mt'])

sc.pp.scale(adata, max_value=10)

sc.tl.pca(adata, svd_solver='arpack')

sc.pl.pca(adata, color='CST3')  # CST3 is a monocyte marker

sc.pl.pca_variance_ratio(adata, log=True)

sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)

sc.tl.umap(adata)
sc.pl.umap(adata, color=['CST3', 'NKG7', 'PPBP'])

pip install igraph

sc.tl.leiden(
    adata,
    resolution=0.9,
    random_state=0,
    flavor="igraph",
    n_iterations=2,
    directed=False,
)

sc.pl.umap(adata, color=['leiden', 'CST3', 'NKG7', 'PPBP'])

sc.tl.rank_genes_groups(adata, 'leiden', method='t-test')
sc.pl.rank_genes_groups(adata, n_genes=25, sharey=False)

# Also try with Wilcoxon (more robust)
sc.tl.rank_genes_groups(adata, 'leiden', method='wilcoxon')
sc.pl.rank_genes_groups(adata, n_genes=25, sharey=False)

# Known PBMC marker genes for each cluster
marker_genes = ['IL7R', 'CD79A', 'MS4A1', 'CD8A', 'CD8B',
                'LYZ', 'CD14', 'LGALS3', 'S100A8', 'GNLY',
                'NKG7', 'KLRB1', 'FCGR3A', 'MS4A7',
                'FCER1A', 'CST3', 'PPBP']

sc.pl.dotplot(adata, marker_genes, groupby='leiden')
sc.pl.stacked_violin(adata, marker_genes, groupby='leiden')

# Map cluster numbers to cell type names
cell_type_map = {
    '0': 'CD4 T cells',
    '1': 'CD14 Monocytes',
    '2': 'B cells',
    '3': 'CD8 T cells',
    '4': 'NK cells',
    '5': 'CD14 Monocytes',
    '6': 'Dendritic cells',
    '7': 'FCGR3A Monocytes',
    '8': 'Platelets',
}

adata.obs['cell_type'] = adata.obs['leiden'].map(cell_type_map)

sc.pl.umap(adata, color='cell_type', legend_loc='on data',
           title='PBMC Cell Types', frameon=False)

adata.write(results_file)
print(f"Saved to {results_file}")