# -*- coding: utf-8 -*-
"""AnnData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DUFZ3oORhpw6rtTRUqy6hdH0eKLBeJfp
"""

!pip install anndata

import numpy as np
import pandas as pd
import anndata as ad
from scipy.sparse import csr_matrix

print(ad.__version__)

counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
adata = ad.AnnData(counts)
print(adata)

# Give meaningful names to rows (cells) and columns (genes)
adata.obs_names = [f"Cell_{i:d}" for i in range(adata.n_obs)]
adata.var_names = [f"Gene_{i:d}" for i in range(adata.n_vars)]

# Inspect the first 10 cell names
print(adata.obs_names[:10])
print(adata.var_names[:10])

# .X holds the actual count data (sparse matrix)
print(type(adata.X))
print(adata.X)

# Convert a small slice to dense for readability
print(adata.X[:5, :5].toarray())

# .obs is a Pandas DataFrame — one row per cell
# Add a cell type annotation column
ct = np.random.choice(["B", "T", "Monocyte"], size=(adata.n_obs,))
adata.obs["cell_type"] = pd.Categorical(ct)  # Categorical = memory efficient

# Add a batch column
adata.obs["batch"] = np.random.choice(["batch1", "batch2"], size=(adata.n_obs,))

print(adata.obs.head(10))
print(adata)  # notice obs now shows in the summary

# .var is a Pandas DataFrame — one row per gene
# Add whether a gene is mitochondrial
adata.var["mt"] = [gene.startswith("MT-") for gene in adata.var_names]

# Add a random mean expression value per gene
adata.var["mean_expr"] = np.array(adata.X.mean(axis=0)).flatten()

print(adata.var.head(10))

# Subset by cell name
subset = adata[["Cell_1", "Cell_10", "Cell_50"], :]
print(subset)

# Subset by boolean mask — only B cells
b_cells = adata[adata.obs["cell_type"] == "B", :]
print(f"Number of B cells: {b_cells.n_obs}")

# Subset by gene name
gene_subset = adata[:, ["Gene_0", "Gene_100", "Gene_500"]]
print(gene_subset)

# .obsm stores 2D/multi-dim arrays aligned to cells
# e.g., PCA coordinates, UMAP coordinates

# Simulate PCA coordinates (100 cells x 10 PCs)
adata.obsm["X_pca"] = np.random.normal(size=(adata.n_obs, 10))

# Simulate UMAP coordinates (100 cells x 2 dims)
adata.obsm["X_umap"] = np.random.normal(size=(adata.n_obs, 2))

print(adata.obsm.keys())
print(adata.obsm["X_umap"][:5])  # first 5 cells' UMAP coords

# .uns is a plain dictionary — store anything here
adata.uns["experiment_name"] = "PBMC Tutorial"
adata.uns["species"] = "Homo sapiens"
adata.uns["color_palette"] = ["#1f77b4", "#ff7f0e", "#2ca02c"]

print(adata.uns)
print(adata.uns["experiment_name"])

# .layers lets you store multiple versions of the data
# Very useful for keeping raw counts alongside normalized data

# Store a "raw counts" layer (simulated)
adata.layers["raw_counts"] = adata.X.copy()

# Store a "log1p normalized" layer (simulated)
import numpy as np
dense = adata.X.toarray()
adata.layers["log1p"] = np.log1p(dense)

print(adata.layers.keys())
print(adata.layers["log1p"][:3, :5])

# Full summary
print(adata)

# Shape
print(f"Cells: {adata.n_obs}, Genes: {adata.n_vars}")

# What's stored where
print("obs columns:", adata.obs.columns.tolist())
print("var columns:", adata.var.columns.tolist())
print("obsm keys:", list(adata.obsm.keys()))
print("layers:", list(adata.layers.keys()))
print("uns keys:", list(adata.uns.keys()))

# Convert expression matrix to a regular Pandas DataFrame
df = adata.to_df()
print(df.shape)
print(df.iloc[:5, :5])

# Save to disk
adata.write_h5ad("my_anndata.h5ad")
print("Saved!")

# Load it back
adata_loaded = ad.io.read_h5ad("my_anndata.h5ad")
print(adata_loaded)

pip install scanpy

pip install igraph

import scanpy as sc

# Reload and reprocess quickly
pbmc = sc.datasets.pbmc3k()
pbmc.var_names_make_unique()

sc.pp.filter_cells(pbmc, min_genes=200)
sc.pp.filter_genes(pbmc, min_cells=3)
pbmc.var['mt'] = pbmc.var_names.str.startswith('MT-')
sc.pp.calculate_qc_metrics(pbmc, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True)
pbmc = pbmc[pbmc.obs.n_genes_by_counts < 2500, :]
pbmc = pbmc[pbmc.obs.pct_counts_mt < 5, :]
sc.pp.normalize_total(pbmc, target_sum=1e4)
sc.pp.log1p(pbmc)
sc.pp.highly_variable_genes(pbmc, min_mean=0.0125, max_mean=3, min_disp=0.5)
pbmc.raw = pbmc
pbmc = pbmc[:, pbmc.var.highly_variable]
sc.pp.regress_out(pbmc, ['total_counts', 'pct_counts_mt'])
sc.pp.scale(pbmc, max_value=10)
sc.tl.pca(pbmc, svd_solver='arpack')
sc.pp.neighbors(pbmc, n_neighbors=10, n_pcs=40)
sc.tl.umap(pbmc)
sc.tl.leiden(pbmc, resolution=0.9, random_state=0, flavor="igraph", n_iterations=2, directed=False)

# Save it properly now
pbmc.write_h5ad("pbmc3k.h5ad")
print("Saved successfully!")
print(pbmc)

print("\n--- Cell metadata (.obs) ---")
print(pbmc.obs.head())

print("\n--- Gene metadata (.var) ---")
print(pbmc.var.head())

print("\n--- Embeddings (.obsm) ---")
print(list(pbmc.obsm.keys()))

print("\n--- Unstructured (.uns) ---")
print(list(pbmc.uns.keys()))

print("\n--- Layers ---")
print(list(pbmc.layers.keys()))